### ISSUE TITLE
Can we use `rustls` instead of `native-tls` by default?

### ISSUE THREAD

**Issue by rinarakaki** [elastic/elasticsearch-rs#219]
**Is your feature request related to a problem? Please describe.**

`reqwest` also uses `rustls` by default. It's better than having an os-specific installation step.

**Describe the solution you'd like**

Before:

```toml
[features]
default = ["native-tls"]
```

After:

```toml
[features]
default = ["rustls-tls"]
```
